# Generated by Django 3.2.16 on 2022-12-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_name_course_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
